spring.application.name=notification-service
server.port=8084

# Production Database (Azure PostgreSQL)
spring.datasource.url=${notification_db_url}
spring.datasource.username=${notification_db_username}
spring.datasource.password=${notification_db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Production Kafka (booking-serv)
spring.kafka.bootstrap-servers=${notification_kafka_bootstrap_servers}
booking.kafka.topic=booking-events

spring.kafka.consumer.group-id=notification-service-group-prd
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.gtbs.notificationservice.notification.dto.BookingEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
