apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8084"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  BOOKING_KAFKA_TOPIC: "booking-events"