apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - service-account.yml
  - configmap.yml
  - secretproviderclass.yml
  - deployment.yml
images:
  - name: ghcr.io/your-org/notification-service
    newName: ghcr.io/your-org/notification-service
    newTag: latest

