apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notification-kv-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: notification-service-secrets
      type: Opaque
      data:
        - objectName: notification-db-url
          key: notification_db_url
        - objectName: notification-db-username
          key: notification_db_username
        - objectName: notification-db-password
          key: notification_db_password
        - objectName: notification-kafka-bootstrap-servers
          key: notification_kafka_bootstrap_servers
  parameters:
    usePodIdentity: "false"
    clientID: "ffbb5ff4-406a-494f-8de9-9776e768f1ed"
    keyvaultName: "ds-gtbs-kv-prod"
    tenantId: "d595be8d-b306-45f4-8064-9e5b82fbe52b"
    objects: |
      array:
        - |
          objectName: notification-db-url
          objectType: secret
        - |
          objectName: notification-db-username
          objectType: secret
        - |
          objectName: notification-db-password
          objectType: secret
        - |
          objectName: notification-kafka-bootstrap-servers
          objectType: secret

